"""add tool_sequence, tool_calls, final_reply to eval_results

Revision ID: 1cfabcd99636
Revises: 1ffacac355f6
Create Date: 2026-09-27 21:54:48.184359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cfabcd99636'
down_revision: Union[str, Sequence[str], None] = '1ffacac355f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eval_results', sa.Column('tool_sequence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('eval_results', sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('eval_results', sa.Column('final_reply', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eval_results', 'final_reply')
    op.drop_column('eval_results', 'tool_calls')
    op.drop_column('eval_results', 'tool_sequence')
    # ### end Alembic commands ###
