"""initial schema: traces and spans

Revision ID: 6cf1e28130d8
Revises: 
Create Date: 2026-08-20 14:02:32.658016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cf1e28130d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traces',
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('project', sa.String(length=64), nullable=False),
    sa.Column('root_span_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_index(op.f('ix_traces_project'), 'traces', ['project'], unique=False)
    op.create_index('ix_traces_project_start_desc', 'traces', ['project', sa.literal_column('start_time DESC')], unique=False)
    op.create_index(op.f('ix_traces_start_time'), 'traces', ['start_time'], unique=False)
    op.create_table('spans',
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.trace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('span_id')
    )
    op.create_index('ix_spans_attributes_gin', 'spans', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_spans_trace_id'), 'spans', ['trace_id'], unique=False)
    op.create_index('ix_spans_trace_start', 'spans', ['trace_id', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spans_trace_start', table_name='spans')
    op.drop_index(op.f('ix_spans_trace_id'), table_name='spans')
    op.drop_index('ix_spans_attributes_gin', table_name='spans', postgresql_using='gin')
    op.drop_table('spans')
    op.drop_index(op.f('ix_traces_start_time'), table_name='traces')
    op.drop_index('ix_traces_project_start_desc', table_name='traces')
    op.drop_index(op.f('ix_traces_project'), table_name='traces')
    op.drop_table('traces')
    # ### end Alembic commands ###
